### PR TITLE
25 users can create accounts

### PR DESCRIPTION
**Pull request by Jeniel557**
Connected the database to the web app. Added fail-safes in case the user's password and their confirming password does not match, or if they did not contain a valid email. 

Cleared the text input area on load or if their input is invalid to add security. 

Set up validation on the database side that only allows unique usernames.

### CODE REVIEW

**Review by TomMakins — COMMENTED** [review]
Looks like something didn't pass. Might be a formatting issue or an unused variable.

Otherwise nice work, good test coverage.

**Comment by Jeniel557** [comment]
> Looks like something never passed. Might be a formatting issue or an unwed variable.
> 
> Otherwise nice work, good test coverage.


Thanks, fixed, I will update the pull request

**Comment by TomMakins** [comment]
Good job, good to have persistence

**Comment by Jeniel557** [comment]
> Good job, tested locally and it seems great!

Thanks for the positive reviews

**Pull request merged**
